### ISSUE TITLE
missing of fs_train.py and fs_test.py

### ISSUE THREAD

**Issue by wlin-at** [Annusha/unsup_temp_embed#1]
Hi, I noticed that the train and test script (`data_utils/FS_utils/fs_train.py` and `data_utils/FS_utils/fs_test.py`) for 50Salads dataset are missing in the repository. Could you also upload them? Thanks for the efforts.

**Comment by Annusha** [comment]
Thanks for notice!
Sure, will do it soon ;)

**Comment by Annusha** [comment]
Done
