### ISSUE TITLE
Global Mode

### ISSUE THREAD

**Issue by spoorgholi74** [Annusha/unsup_temp_embed#3]
Hi Annusha,
Thanks for your work.

I was wondering if you have time to complete the training for the global model which we don't train for a specific class?
Because I could not get the global branch to work.

**Comment by Annusha** [comment]
Hi!

I'm sorry for the delay. I'm working to make it public now, it'll be available soon.

**Comment by snorkeldepth** [comment]
Awesome 🕶 Thanks a lot again, really appreciate your concept 👍👍
