### ISSUE TITLE
What is the function of "resume_str" in line 99 of corpus.py?

### ISSUE THREAD

**Issue by Darshansingh11** [Annusha/unsup_temp_embed#7]
Hi Anna,
Thank you for making the code available. I just had a small concern. I am trying to run the code by setting model_name='nothing' (using just the raw features). However, I am getting the following error from [line 99 of corpus.py](https://github.com/Annusha/unsup_temp_embed/blob/master/ute/corpus.py#L99). 

> AttributeError: 'Namespace' object has no attribute 'resume_str'

I then checked that "resume_str" is not part of the namespace. Please let me know what "resume_str" is.
Thank you.

**Comment by Annusha** [comment]
Hi @Darshansingh11,

thanks a lot for your interest! You can define this parameter as you need or just delete it. The only influence is setting the correct path to your features. 
Hope it helps!
